apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderservicedb-pvc
spec:
  storageClassName: manual
  volumeName: nfs-pv
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
