apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderservicedb-pvc
spec:
  storageClassName: local-nfs-storage # name of nfs sc
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
